Repository UofT-CS-Group/CSC110-Final-Project, pull requests merged in 2021-12, with the labels that each got.

#33 Add Rename Main Window under Edit Menu
  Application/gui_main.py
Labels: enhancement

#34 Optimize cross-hair FPS and add zoom, pan.
  Application/gui_main.py
Labels: enhancement, fix

#37 Modify the icon a little bit
  Application/resources/assets/about_page.png
  Application/resources/assets/icon.png
Labels: enhancement

#32 Added menu bar
  Application/gui_main.py
  Application/gui_utils.py
  Application/resources/assets/about_page.png
Labels: enhancement

#46 A slightly better implementation of config resource system.
  Application/config.json
  Application/data.py
  Application/gui_main.py
  Application/main.py
  Application/requirements.txt
  Application/resource_manager.py
  Application/settings.py
Labels: enhancement

#48 Added a lot of Docstrings & Edited some Docstrings & Added Type annotations for some functions
  Application/data.py
  Application/gui_main.py
  Application/gui_utils.py
  Application/resource_manager.py
  Application/settings.py
Labels: documentation

#47 Fix sliders value changed event.
  Application/gui_main.py
Labels: fix

#51 Added functionality to Reset Plot
  Application/gui_main.py
Labels: enhancement

#54 Make country searching even more normal and "intelligent" lol
  Application/gui_main.py
Labels: enhancement

#53 Fix search bug
  Application/gui_main.py
Labels: fix
